#! /bin/sh
# ipmi_sim_lancontrol - provide link addresses to ipmi_sim for device $1
# See lan_config_program in ipmi_lan(5)
#
# 2015-05-06  Noel Burton-Krahn <noel@pistoncloud.com>

set -eu

# arguments: dev op var
# network interface
dev=$1
# get or set.  This script just supports get
op=$2
# var name
var=$3

# my default gateway device
gw_dev=$(ip route | sed -ne 's/default via [.0-9]* dev \([^ ]*\) .*/\1/p')

link_ip() {
    ip -o -4 addr list $1 | sed -ne 's/.* inet \([.0-9]*\)\/.*/\1/p'
}

link_mac() {
    ip -o link list $1 | sed -ne 's/.* link\/ether \([:0-9a-f]*\) .*/\1/p'
}

link_subnet() {
    ifconfig $1 | sed -n -e 's/.*Mask:\([.0-9]*\).*/\1/p'
}

get_val() {
    case $var in
	ip_addr_src)
	    echo "dhcp"
	    ;;

	ip_addr)
	    link_ip $dev
	    ;;
	
	mac_addr)
	    link_mac $dev
	    ;;

	subnet_mask)
	    link_subnet $dev
	    ;;

	default_gw_ip_addr)
	    link_ip $gw_dev
	    ;;
	
	default_gw_mac_addr)
	    link_mac $gw_dev
	    ;;
	    
	backup_gw_ip_addr)
	    link_ip $gw_dev
	    ;;
	
	backup_gw_mac_addr)
	    link_mac $gw_dev
	    ;;
    esac
}

if [ $op = "get" ]; then
    val=$(get_val $var)
    echo "$var: $val"
fi

